services:
  - type: web
    name: ahmuko-backend
    env: node
    buildCommand: cp backend-package.json package.json && npm install
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        sync: false
